### ISSUE TITLE
2019_1

### ISSUE THREAD

**Issue by tse-gratis** [pkomagum/Advent-of-code-trials#1]
Great, it looks like you've got a good function working. Now because we will get the values as a file or string, rather than int fuel1, fuel2, fuel3, fuel4... Lets place them in a single multiline string

char mystr[] =
"12\n"
"14\n"
"1969\n"
"100756"

Then can you print the integer values from that string? Maybe stoi (string to int) to get the first fuel value, and print that. Then use a while loop to print the first and every int after each \n newline character

Once you can print those, you can change from `printf("%d\n", stoi(mystr[n]))` to `printf("%d\n", fuelcomputer(stoi(mystr[n])));`

**Comment by pkomagum** [comment]
Good twist. Let me make that happen. and try to see if all the inputs can be done using a "For loop" rather than having preset inputs.

**Comment by pkomagum** [comment]
Though I will implement the input process using integers for now, and later on change it to strings in another branch.

**Comment by pkomagum** [comment]
Have a look at the way thought process using integers. the program runs properly. and seems to compute properly.

**Comment by tse-gratis** [comment]
Yup. Well done :+1:
